import type { Metadata } from "next";
import { Caveat } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { Header, Footer, ScrollToTopBtn } from "./global-components/exports";
import Logic from "./contexes/Logic";
import "./globals.css";

const caveat = Caveat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth overflow-x-hidden">
      <body className={`${caveat.className} bg-primary text-text`}>
        <Logic>
          <Header />
          {children}
          <Footer />
          <ScrollToTopBtn />
        </Logic>
        <Toaster
          position="bottom-left"
          toastOptions={{
            style: {
              background: "#00ADB5",
              color: "#EEE",
              fontSize: 22,
              fontWeight: "bold",
            },
          }}
        />
      </body>
    </html>
  );
}
