import type { Metadata } from "next";
import { Caveat } from "next/font/google";
import { Header, Footer } from "./global-components/exports";
import "./globals.css";
const caveat = Caveat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${caveat.className} bg-primary text-text`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
